# -*- coding: utf-8 -*-
"""combine_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LnP1PIL3X1dmWQNZSON7rybPs7EipymI
"""

import pandas as pd
import os

!pip install pyspark

transac = pd.read_csv('/content/drive/MyDrive/diggibyte/spark_1/transaction.csv')
user = pd.read_csv('/content/drive/MyDrive/diggibyte/spark_1/user.csv')

transac

col = {'userid' : 'user_id'}

transac.rename(columns = col, inplace=True)

user

transac

transac

user

outer = pd.merge(transac, user, on='user_id', how='outer')

pd.merge(transac, user, on='user_id', how='inner')

outer = pd.DataFrame(outer)

outer.columns

df.csv('other_.csv')

outer.to_csv('outer_join.csv')

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Python Spark SQL basic example").config("spark.some.config.option", "some-value").getOrCreate()

df = spark.read.csv('outer_join.csv')

df.show()

final = spark.read.option('inferSchema' , True).option('header', True).csv('outer_join.csv')

final.show()

final.printSchema()

final

final.select('location ')

final.groupby('location ').count().show()

final = spark.read.csv('outer_join.csv' , inferSchema=True, header=True)

final

final.columns

final.printSchema()

for i in final.head(5):
  print(i, '\n')

final.show()

final.groupby('location ').count().show()

final.printSchema()

final.select('product_description').show()

final.select('price')

final.groupBy("user_id", "product_description").avg('price').show()

final.printSchema()

transac

user

df = pd.merge(transac, user, on='user_id', how='inner')

df.to_csv('inner_join.csv')

inner = spark.read.option('inferSchema', 'True').option('header', 'True').csv('inner_join.csv')

inner.show()

inner.columns

inner.groupby('location ').count().show()

final.groupby('location ').count().show()

inner.groupBy("user_id", "product_description").avg('price').show()

inner.groupBy("user_id", "product_description").count().show()

